add Business Insider
flairNLP/fundus pull request #341
Opened 2024-01-29 21:57 UTC by MaxDall

Adds [Business Insider](https://www.businessinsider.de/) as a publisher.

2024-01-30 19:33 UTC, addie9800 requested changes
Thanks for adding this

2024-01-30 19:33 UTC, addie9800 commented on src/fundus/publishers/de/business_insider.py
> +        )
Some articles are incomplete due to the known issue with the paywall (e.g. https://www.businessinsider.de/wirtschaft/finanzen/ich-bin-29-jahre-alt-und-habe-6-immobilien-gekauft-das-sind-meine-5-tipps-wie-auch-ihr-das-schaffen-koennt/) not sure what can be done about it though

2024-01-30 19:33 UTC, addie9800 commented on src/fundus/publishers/de/business_insider.py
> +            return generic_topic_parsing(self.precomputed.meta.get("keywords"))
It seems to just occur within the insider-picks section of articles (another example https://www.businessinsider.de/insider-picks/technik/smartphones-unter-200-euro-empfehlungen/)

2024-01-31 10:16 UTC, MaxDall commented
Oh wow, awesome 👍 Thanks for this really in depth review. Especially the link's to all the edge cases helping a lot. How did you find them?

2024-01-31 14:28 UTC, addie9800 commented
No problem. I crawled 50 articles and printed the title, authors, plaintext, url and topics. I then skimmed over the output and then I can check out the articles everytime something seems weird.

2024-02-01 16:43 UTC, MaxDall commented on src/fundus/publishers/de/__init__.py
> +        sources=[
Normally `NewsMap` and `Sitemap` are enough.

2024-02-01 16:46 UTC, MaxDall commented on src/fundus/publishers/de/business_insider.py
> +        )
> You could add or @class='has-text-align-right'

Good idea!

> Some articles are incomplete due to the known issue with the paywall

Sadly not that much. But judging by the article that's a cookie and not a paywall problem. I see what i can do.

2024-02-01 17:29 UTC, MaxDall commented on src/fundus/publishers/de/business_insider.py
> +        def title(self) -> Optional[str]:
I would stick to the rest of the parser and go with whatever is included in the ld.

2024-02-01 17:29 UTC, MaxDall commented on src/fundus/publishers/de/business_insider.py
> +            return generic_topic_parsing(self.precomputed.meta.get("keywords"))
I added some code to handle with this edge case

2024-02-05 09:55 UTC, addie9800 approved these changes
Looks good 👍

2024-02-06 14:49 UTC, merged