Add query parameter
flairNLP/fundus pull request #403
Opened 2024-04-06 13:06 UTC by addie9800

This PR is a rebrand of and closes #392 where the code is changed to work with #357 
The major change compared to the former version ist that the query_parameter attribute accepts a dictionary of key value pairs. Adding Heise will be done in a separate PR

2024-04-18 14:57 UTC, MaxDall requested changes
@addie9800 Thanks for adding. Looks like a great feature :)

2024-04-18 14:57 UTC, MaxDall commented on scripts/generate_parser_test_files.py
> +        source = WebSource([url], publisher=enum.publisher_name, query_parameters=enum.query_parameter)
Since this is about crawling a specified URL we should not pass the query parameter here.

2024-04-18 14:57 UTC, MaxDall commented on src/fundus/scraping/html.py
> +        self.query_parameters = query_parameters
i would suggest

```python
self.query_parameters = query_parameters or {}
```

and remove

```python
if self.query_parameters is not None:
```

2024-04-19 10:44 UTC, addie9800 commented on src/fundus/scraping/html.py
> +        self.query_parameters = query_parameters
Sounds good

2024-04-19 10:50 UTC, MaxDall requested changes

2024-04-19 10:50 UTC, MaxDall commented on src/fundus/scraping/html.py
> +                        url += "?" + key + "=" + value
Sorry, one last thing i missed: This should be outside the `try ... catch` block.

2024-04-19 11:43 UTC, MaxDall approved these changes

2024-04-19 11:50 UTC, merged