added Bayerischer Rundfunk as publisher
flairNLP/fundus pull request #435
Opened 2024-04-21 04:18 UTC by MK2112

Hey, I added the German "Bayerischer Rundfunk" as publisher. I also generated and ran tests as per the [guidelines](https://github.com/flairNLP/fundus/blob/master/docs/how_to_add_a_publisher.md) and added the new publisher to `supported_publishers.md`.

2024-04-22 11:07 UTC, MaxDall commented
Hey @MK2112, there seems to be something of with your test case. It includes duplicate content as well as `headlines` with no actual selector set. Could you run `python -m scripts.generate_parser_test_files -p BR -oj` and push the changes´.

2024-04-22 16:42 UTC, MaxDall requested changes
Thanks for adding :)

2024-04-22 16:42 UTC, MaxDall commented on src/fundus/publishers/de/br.py
> +            # TODO
```suggestion
```

2024-04-27 11:03 UTC, MaxDall approved these changes

2024-05-05 21:01 UTC, addie9800 approved these changes

2024-05-05 21:01 UTC, merged