add-publisher-wdr
flairNLP/fundus pull request #439
Opened 2024-04-22 13:01 UTC by jannispoltier

Hi, I added the WDR (Westdeutscher Rundfunk) to the collection of German publishers and ran all tests and commands as instructed. 
There is just one issue I couldn't resolve as for some article summaries the crawler returns a `<p class="stand small">` element although I added an XPath to return `<p class="einleitung small">` and this element did exist in the given file. However, I couldn't come up with a fix for that problem. Maybe you have a suggestion :)

2024-04-22 16:25 UTC, MaxDall requested changes

2024-04-22 16:25 UTC, MaxDall commented on src/fundus/publishers/de/wdr.py
> +        _subheadline_selector = XPath("//article//h2")
```suggestion
        _subheadline_selector = XPath("//article//h2[@class='subtitle small']")
```

2024-04-22 16:25 UTC, MaxDall commented on src/fundus/publishers/de/wdr.py
> +            return self.precomputed.ld.bf_search("name")
```suggestion
            return self.precomputed.meta.get("og:title")
```

2024-04-23 10:43 UTC, MaxDall commented
Hey, @jannispoltier could you rerun `python -m scripts.generate_parser_test_files -p WDR -oj` and push the modified JSON file? You don't have to remove the old test case, just run the script with `-oj` flag :)

2024-04-23 13:16 UTC, jannispoltier commented
> Hey, @jannispoltier could you rerun `python -m scripts.generate_parser_test_files -p WDR -oj` and push the modified JSON file? You don't have to remove the old test case, just run the script with `-oj` flag :)

Hi @MaxDall, I pushed the file and on my local machine the tests were now successful ☺️

2024-04-27 11:05 UTC, MaxDall approved these changes

2024-04-27 11:18 UTC, MaxDall approved these changes

2024-05-05 21:15 UTC, addie9800 approved these changes

2024-05-05 21:15 UTC, merged