add daily star support
flairNLP/fundus pull request #443
Opened 2024-04-22 18:43 UTC by Jabbawukis

2024-04-23 10:40 UTC, MaxDall requested changes
Thanks for adding :)

2024-04-23 10:40 UTC, MaxDall commented on src/fundus/publishers/uk/daily_star.py
> +            return generic_topic_parsing(self.precomputed.meta.get("article:tag"))
```suggestion
            return generic_topic_parsing(self.precomputed.meta.get("keywords"))
```

2024-04-23 10:40 UTC, MaxDall commented on src/fundus/publishers/uk/daily_star.py
> +        _paragraph_selector = CSSSelector("div.article-body")
```suggestion
        _paragraph_selector = XPath("//div[@class='article-body'] /p[text()]")
```

2024-04-23 11:03 UTC, Jabbawukis commented
fix Xpath import and update unit tests -> checks pass now

2024-04-27 11:35 UTC, MaxDall approved these changes

2024-05-06 10:45 UTC, merged