Add Hessenschau
flairNLP/fundus pull request #472
Opened 2024-04-27 07:48 UTC by martinknz

2024-04-28 19:57 UTC, MaxDall requested changes
Thanks for adding 👍

2024-04-28 19:57 UTC, MaxDall commented on src/fundus/publishers/de/__init__.py
> +            Sitemap("https://www.hessenschau.de/indexsitemap.nc.xml"),
```python
            RSSFeed("https://www.hessenschau.de/index.rss"),
            NewsMap("https://www.hessenschau.de/newssitemap.nc.xml"),
            Sitemap("https://www.hessenschau.de/sitemap.nc.xml"),
```

2024-04-28 19:57 UTC, MaxDall commented on src/fundus/publishers/de/hessenschau.py
> +        _paragraph_selector = CSSSelector("p.copytext__text.text__copytext")
It seems that the first paragraph is often but not always the article summary.

2024-04-28 19:57 UTC, MaxDall commented on src/fundus/publishers/de/hessenschau.py
> +            return generic_date_parsing(self.precomputed.meta.get("article:published_time"))
Could you add `authors` and `topics` as well? You can find both of them in the meta tags. Just refer to other parsers to see how to extract them.

2024-04-29 16:15 UTC, MaxDall commented
@martinknz I fixed both selectors for you. This should be good to go now.

2024-04-29 16:16 UTC, MaxDall approved these changes

2024-05-05 21:20 UTC, addie9800 approved these changes

2024-05-05 21:20 UTC, merged