Add new publisher Vogue
flairNLP/fundus pull request #477
Opened 2024-04-28 10:45 UTC by Oreo7985

2024-04-29 11:28 UTC, MaxDall requested changes
Thanks for adding 👍 this one looks really good!

2024-04-29 11:28 UTC, MaxDall commented on src/fundus/publishers/de/vogue.py
> +        _subheadline_selector = XPath("//article//h2")
This newspaper seems to support a little `summary` as well. An example would be [this article](https://www.vogue.de/artikel/jennifer-garner-outfit-hellblau-rot-sommer-2024). In Fundus context the summary would be
```
Hellblau und Rot wirken als Trendfarben allein schon stilvoll – Jennifer Garner beweist nun, wie genial die Kombination der beiden im Frühjahr/Sommer 2024 sein kann.
```

Further the selectors  are a bit too unspecific, extracting a lot of text unrelated to the article like

```
Von Katharina Fuchs
Mehr Themen auf Vogue.de:
Von Katharina Fuchs
Von Katharina Fuchs
Von Gabi Thorne
Von Marie Périer
Von Héloïse Salessy, Vogue Germany
Von Alessandra Signorelli
```

All of those are taken from the article I mentioned above.

2024-04-29 11:29 UTC, MaxDall requested changes

2024-04-29 11:29 UTC, MaxDall commented on src/fundus/publishers/de/__init__.py
> +    Vogue = PublisherSpec(
Could you rename the publisher to `VogueDE`

2024-04-30 13:58 UTC, Oreo7985 commented
Hi Max, I have fixed the problems you mentioned. Please review the code again and see if the PR can be committed. Thanks! @MaxDall

2024-04-30 20:16 UTC, MaxDall commented
@Oreo7985 I adjusted the selectors.

2024-04-30 20:16 UTC, MaxDall approved these changes

2024-05-06 17:10 UTC, merged