Add new publisher TechCrunch.com
flairNLP/fundus pull request #480
Opened 2024-04-28 14:08 UTC by jannichorst

2024-04-29 12:59 UTC, MaxDall requested changes
Thanks for adding 👍 this one looks really good! Just two minor things.

2024-04-29 12:59 UTC, MaxDall commented on src/fundus/publishers/us/__init__.py
> +        domain="https://www.techcrunch.com/",
```suggestion
        domain="https://techcrunch.com/",
```

2024-04-29 12:59 UTC, MaxDall commented on src/fundus/publishers/us/techcrunch.py
> +            # return title
```suggestion
```

2024-04-29 17:26 UTC, jannichorst commented
Glad it looks good! Committed the changes. Let me know if anything else has to be done :)

2024-04-30 20:30 UTC, MaxDall submitted a review, later dismissed

2024-05-06 17:15 UTC, merged