Publisher Collection Rework
flairNLP/fundus pull request #526
Opened 2024-05-23 13:53 UTC by addie9800

This PR replaces the `PublisherEnum`, `PublisherCollection` and `PublisherSpec` types with two new types: `Publisher` and `PublisherGroup`. 

Note: I haven't done the documentation yet, I thought it might be better to first get the code approved and then update the documentation to avoid unnecessary double work.

2024-05-30 12:04 UTC, MaxDall requested changes
Thanks for tackling one of the open problems ;) I would suggest going over this in iteration and for now I tried to address most of the structural/basic problems.

2024-05-30 12:04 UTC, MaxDall commented on tests/utility.py
> +    return generate_absolute_section_path(publisher) / f"{publisher.publisher_name}.json"
We might rewrite this part so that we don't need to keep `publisher_name`.

2024-05-30 12:35 UTC, addie9800 commented on src/fundus/publishers/base_objects.py
> +    _contents: Set[str]
The idea was that those two elements are needed every once in a while and I thought this way we would avoid iterating through all subgroups to get the length and similarly for the direct attributes of the PublisherGruoup

2024-05-30 12:43 UTC, addie9800 commented on src/fundus/publishers/base_objects.py
> +        return False
Good Question, I am not sure we used it, but it was part of the previous implementation, so I decided to keep it :)

2024-05-30 12:45 UTC, addie9800 commented on src/fundus/publishers/base_objects.py
> +                raise AttributeError(f"Element {element} of invalid type {type(element)}")
Sounds good

2024-06-02 18:14 UTC, addie9800 commented on docs/supported_publishers.md
> +        <code>Der Standard</code>
Yep, they did, it's fixed

2024-06-02 18:30 UTC, addie9800 commented on scripts/publisher_coverage.py
> +        publisher: Publisher
Tbh, I don't think there are any left that are related to the publisher enum

2024-06-02 18:37 UTC, addie9800 commented on src/fundus/publishers/base_objects.py
> +        @param request_header: Request header to be used for the GET-request
Ah yeah. I think I knew that at some point... I have fixed it.

2024-06-02 22:20 UTC, addie9800 commented on src/fundus/publishers/base_objects.py
> +        self.publisher_name: Optional[str] = None
But don't we need both names? At the very least in the supported_publishers.md file both names are referenced. I fixed the rest :)

2024-06-02 22:32 UTC, addie9800 commented
Thanks for the very thorough review :)

2024-06-02 22:40 UTC, addie9800 commented on src/fundus/publishers/base_objects.py
> +        self.publisher_name: Optional[str] = None
I modified the utility function slightly, this way we don't need the extra attribute at all. But I guess it's also not the most elegant solution

2024-06-07 10:36 UTC, addie9800 commented
I took the chance to also integrate the suggested changes, closing #498

2024-07-02 16:23 UTC, MaxDall commented
@addie9800 I finished working on this, could you give it a look?

2024-07-02 16:56 UTC, addie9800 commented
Looks good as far as I can see. I updated the documentation to reflect the new old `_PublisherCollectionMeta`.

2024-07-02 17:27 UTC, MaxDall approved these changes
🚀

2024-07-02 19:01 UTC, merged