Add search by language functionality
flairNLP/fundus pull request #667
Opened 2024-12-21 14:30 UTC by addie9800

As mentioned in #638 by @MaxDall , we need a better solution to handle different languages. This PR is a proposal for a solution to this issue. The idea is that you can tag each URLSource object, with the corresponding languages. It would be ideal to do it at URLSource level, since some publishers differentiate their sitemaps/feeds by language and we could then do the same.

Once the sources are tagged, we can then use the search functionality of the PublisherGroup which creates an internal filter only allowing access to those URLSources tagged with one of the languages, that are wanted. 

Note, that I haven't yet thoroughly tested everything, I just wanted to get a working version of it, for you to have a look at and say what you think before putting too much effort into it. I would add tests and documentation in a further step.

2025-04-03 12:35 UTC, MaxDall requested changes
@addie9800 Thanks a lot 🙏 This PR is an excellent addition to FUNDUS.

2025-04-03 12:35 UTC, MaxDall commented on src/fundus/scraping/scraper.py
> +                            logger.debug(f"Skipped article at {html.requested_url!r} because of language filter")
I think it would be beneficial to print out the language mismatch as well

2025-04-06 14:35 UTC, addie9800 commented on src/fundus/publishers/na/__init__.py
>          domain="https://www.namibian.com.na/",
Sounds good to me, I will change that

2025-04-06 15:00 UTC, addie9800 commented on src/fundus/publishers/base_objects.py
> +                        self._language_filter = unique_languages
Good idea, I split the language and source type logic into separate functions to make it clearer and cleaner

2025-04-07 14:59 UTC, addie9800 commented on src/fundus/publishers/base_objects.py
> +                        self._language_filter = unique_languages
That's a good point. I have addressed that in the new changes. I have decided to return a copy, That seemed like the most effective choice in this position.

2025-04-07 16:00 UTC, addie9800 commented on src/fundus/scraping/crawler.py
> +                    tuple(fitting_publishers), error_handling, build_extraction_filter(), url_filter, language_filter
Making the lang attribute defailt in the BaseParser proved to be more of a hassle than originally expected, which is why I would leave it the way it is. The main issue is that the lang attribute requires the plaintext of the article, which will only be available after the actual parser has run. It would also require to make the parsed_data a class attribute and we need to guarantee that the lang attribute is computed after the body.

This is why I think we should keep this the way it is.

2025-04-07 16:02 UTC, addie9800 commented on src/fundus/scraping/crawler.py
> +                    tuple(fitting_publishers), error_handling, build_extraction_filter(), url_filter, language_filter
Regarding the language filter: I think that could also lead to counter intuitive behavior. If we limit ourselves to a single default language, this will cause unexpected behavior for example when running Fundus for the Indian PublisherGroup, which will only return articles from Bhaskar and not Times of India.

2025-04-07 16:03 UTC, addie9800 commented on docs/5_advanced_topics.md
> +fitting_publishers = PublisherCollection.us.search(attributes=["topics"], source_types=[NewsMap], languages=["es"])
Good point, I think I have found a solution for that. The main question is how to handle additional filters that could be passed into the crawl function. For now I decided to unionize them, maybe you can let me know what you think.

2025-04-08 09:55 UTC, MaxDall commented on src/fundus/scraping/crawler.py
> +                    tuple(fitting_publishers), error_handling, build_extraction_filter(), url_filter, language_filter
Thanks a lot for sharing your thoughts. I agree with your concerns. Let's leave it as is then 👍

2025-04-15 11:32 UTC, MaxDall requested changes
@addie9800 Could you go over the documentation one last time in order to check if everything regarding filtering publishers, languages etc. is still correct? Besides that, everything looks good now!

2025-04-15 14:35 UTC, MaxDall approved these changes
@addie9800 Thanks a lot for adding this ❤️

2025-04-15 14:36 UTC, merged